
# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(boni1BqWUxCpK0DyiITXtw==)
    password: ENC(UHtdSW/UQ8CqC473F38zLUmoosCPAACV)
    url: jdbc:mysql://db.githink.cn:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
